### PR TITLE
Gb/fix gpool

### PR DESCRIPTION
**Pull request by grantbuster**

### CODE REVIEW

**Comment by grantbuster** [comment]
@bnb32 option to review. The goal here is to implement a pooling layer with a gaussian kernel instead of a uniform average. i flip flopped between a tensorflow conv2d layer (implemented in the previous PR) with fixed kernel versus applying a kernel directly with the tf convolution method. The conv2d layer won't actually work because this needs to operate on each feature independently and a conv2d will apply a uniform kernel to all features and then sum across all features yielding a constant output.

**Review by bnb32 — APPROVED** [review]
Cool. Were you thinking this might help with sharp edged artifacts?

**Comment by grantbuster** [comment]
> Cool. Were you thinking this might help with sharp edged artifacts?

huh maybe but no i implemented this for the UHI work where we're training simple networks on point observations but want to include some input wide-field spatial information.

**Comment by bnb32** [comment]
> > Cool. Were you thinking this might help with sharp edged artifacts?
> 
> huh maybe but no i implemented this for the UHI work where we're training simple networks on point observations but want to include some input wide-field spatial information.

ah yeah makes sense.

**Pull request merged**
